name: GitHub Actions Pipelinee
on:
 push:
  branches:
    - main
jobs:
 invoke_api:
  runs-on: windows-latest
  steps:
    - name: Call REST API
      run: |
       $BatchscheduleID = '${{ vars.VikasTest }}'
        $params = @{
          Uri = 'http://3.6.189.154:8080/test-automation-via-cicd'
          Method = 'POST'
          Body = @{
            Usernameofbreez = 'sarrofsa01@gmail.com'
            Passwordofbreez = 'Sonu@1234'
            BatchscheduleID = $BatchscheduleID
          }
        }
        Invoke-RestMethod @params
